log-level: error

all: false
recursive: false

dir: '{{.InterfaceDir}}'
structname: '{{.Mock}}{{.InterfaceName}}'
pkgname: '{{.SrcPackageName}}'
force-file-write: true

formatter: goimports
template: testify

packages:

  github.com/lucaspopp-wbd/mockery-issue:
    config:
      recursive: true
      all: true

  github.com/istreamlabs/go-sdk/isp:
    config:
      recursive: true
      all: true
      pkgname: mocks
      dir: mocks
    interfaces:
      ChannelsForOrganizationApi:
